name: "Nombre contenedor Docker"
on:
  workflow_run:
    workflows: ["Extrae usuario y repo"]
    paths:
      - 'proyectos/hito-[34567].md'
    types: completed

jobs:
  docker_get:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga valores
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: extrae-usuario-repo.yaml
          workflow_conclusion: success
          name: user-repo
      - name: Crea variables de entorno
        run: |
          cat USER_REPO
          cat USER_REPO >> $GITHUB_ENV
      - name: Descarga repo usuario y ejecuta contenedor
        uses: actions/checkout@v2
        with:
          repository: '${{env.IV_USER}}/${{env.IV_REPO}}'
      - name: Halla nombre de contenedor
        run: |
          if test -f "DOCKER_USER"; then
            echo "Usuario de Docker alternativo"
            IV_USER=`cat DOCKER_USER`
          fi
          echo "CONTAINER=${IV_USER}/${IV_REPO}" >> IV_CONTAINER
      - name: "Sube el fichero"
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.IV_USER}}-iv-container
          path: IV_CONTAINER

