name: "Crea artefacto con configuración"
on:
  workflow_run:
    workflows: ["Extrae usuario y repo"]
    types: completed

jobs:
  sube_config:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga valores
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: extrae-usuario-repo.yaml
          workflow_conclusion: success
          name: user-repo
      - name: Crea variables de entorno
        run: |
          cat USER_REPO >> $GITHUB_ENV
      - name: Descarga repo usuario y ejecuta contenedor
        uses: actions/checkout@v2
        with:
          repository: '${{env.IV_USER}}/${{env.IV_REPO}}'
      - name: Descarga ysh y ejecuta
        run: |
          sudo curl -s -L https://raw.githubusercontent.com/azohra/yaml.sh/v0.2.0/ysh --output /usr/bin/ysh
          sudo chmod +x /usr/bin/ysh
          ysh -v
          curl https://raw.githubusercontent.com/JJ/IV-20-21/master/.github/workflows/procesa_yaml.sh --output procesa_yaml.sh
          chmod +x ./procesa_yaml.sh
          ./procesa_yaml.sh
      - name: "Sube el fichero"
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.IV_USER}}-iv-config
          path: IV_CONFIG
